version: '3'
services:
  web:
    restart: always
    image: "docker.bintray.io/jfrog/artifactory-pro:latest"
    container_name: artifactory
    ports:
      - "8081:8081"
    volumes:
      - /var/opt/jfrog/artifactory:/var/opt/jfrog/artifactory
    build:
      context: ./

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  10.103.0.0/24
